#!/bin/bash 
# O código tem a finalidade de mostrar uma mensagem caso o espaço do disco passe do valor determinado. Assim a mensagem irá imprimir a data na hora junto com os minutos e os segundos.

VAR=$(df -h | grep overlay | awk '{print $5}' | cut -d "%" -f1)

if [ $VAR -gt 75 ]
then
   echo "$(date +'%Y-%m-%d %H:%M:%S') - OCUPACAO DO DISCO ACIMA DO LIMITE DE $VAR%"
else
   echo "O parametro esta ok"
fi
